name: Remote SSH

on:
  push:
    branches: [ "main,master" ]
  pull_request:
    branches: [ "main,master" ]

  workflow_dispatch:


jobs:
  testing01:
    name: default flag testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: correct password but wrong key
        uses: ./
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SEVER_SSH_KEY}}
          port: ${{ secrets.PORT }}
          script: git pull
