name: Remote SSH

on:
  push:
    branches: [ "main,master" ]
  pull_request:
    branches: [ "main,master" ]

  workflow_dispatch:


jobs:
  testing01:
    name: default flag testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: executing remote ssh commands using ssh key
        uses: ./
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
